version: "3.5"

services:
  tesla_trip_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - tesla-trip-proxy
    environment:
      - PMA_HOST=tesla_trip_mysql
      - UPLOAD_LIMIT= 2000M
    ports:
      - "8000:80"
    volumes:
      - ./config/phpmyadmin/config.inc.php:/etc/phpmyadmin/config.inc.php
    container_name: tesla_trip_phpmyadmin
  tesla_trip_mysql:
    image: mysql/mysql-server:5.7
    networks:
      - tesla-trip-proxy
    environment:
      - TZ=Asia/Taipei
      - MYSQL_ROOT_PASSWORD=root@root@root
    volumes:
      - ./init_data:/docker-entrypoint-initdb.d
      - ./db/mysql/mysql_data:/var/lib/mysql
      - ./config/mysql/my.cnf:/etc/mysql/my.cnf
    container_name: tesla_trip_mysql
  tesla_trip_redis:
    image: redis:5.0
    networks:
      - tesla-trip-proxy
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./db/redis/redis_data:/data
    container_name: tesla_trip_redis

networks:
  tesla-trip-proxy:
    external:
      name: tesla-trip-network
