version: '3.5'

services:
  nginx:
    container_name: nginx
    image: nginx:1.14.2
    volumes:
      - ./default/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./default/default.conf:/etc/nginx/conf.d/default.conf:rw
      - ./tesla_trip.conf:/etc/nginx/conf.d/tesla_trip.conf
      - ./image.conf:/etc/nginx/conf.d/image.conf:rw
      - ~/image:/image
    networks:
      - tesla-trip-proxy
    ports:
      - "80:80"
      - "443:443"

networks:
  tesla-trip-proxy:
    external:
      name: tesla-trip-network
